### ISSUE TITLE
Repeated cells in ODS file are blank

### ISSUE THREAD

**Issue by dominique-unruh** [chfw/pyexcel-ods#1]
When reading an ODS file and a cell has repeated values, pyexcel-ods will give the repeated cells an empty value.
The problem is in ODSSheet.to_array:

    repeat = cell.getAttribute("numbercolumnsrepeated")
    if(not repeat):
      has_value = True
      ret = self._read_cell(cell)
      arrCells.append(ret)
    else:
      r = int(repeat)
      for i in range(0, r):
        arrCells.append("")

Is should be:

    repeat = cell.getAttribute("numbercolumnsrepeated")
    if(not repeat):
      has_value = True
      ret = self._read_cell(cell)
      arrCells.append(ret)
    else:
      r = int(repeat)
      ret = self._read_cell(cell) # Fixed
      for i in range(0, r):
        arrCells.append(ret) # Fixed

**Comment by chfw** [comment]
Please let me if the fix works for you as well. I will then release it to pypi.

**Comment by dominique-unruh** [comment]
Hi,

I copied __init__.py from the fix over my installation, and it works fine
now.
Thanks for the quick reaction.

Best wishes,
Dominique.
