### ISSUE TITLE
ValueError: invalid literal for int() ...

### ISSUE THREAD

**Issue by joaoe** [chfw/pyexcel-ods#3]
Howdy.
I have an ODS file in which there is a column with a custom date/time format (yyyy-mm-dd hh:mm). The file was generated by libreoffice.
The xml for a cell in that column is
`<table:table-cell table:style-name="ce4" office:value-type="date" office:date-value="2015-08-17T19:20:00" calcext:value-type="date"><text:p>2015-08-17 19:20</text:p></table:table-cell>`

So, when loading that file, I get the error
`File "/usr/local/lib/python2.7/dist-packages/pyexcel_ods/__init__.py", line 56, in date_value
    day = int(tokens[2])
ValueError: invalid literal for int() with base 10: '17T19:10:00'`
because the code is expecting the data to be in the format yyyy-mm-dd.

The safest bet would be to always use `dateutil.parser.parse(value)` which handles the iso format.

**Comment by chfw** [comment]
It made sense. I will find the time to correct it.

**Comment by chfw** [comment]
Before I publish it to pypi, could you help verify it? Here is the command:

    pip install git+https://github.com/chfw/pyexcel-ods.git

**Comment by joaoe** [comment]
Sure, but...
`Could not find any downloads that satisfy the requirement python-dateutils==2.4.2 (from pyexcel-ods==0.0.10)`
Does it make sense to add a dependency with dateutil ? The package is installed by default.

Anyway, I don't think this code is entirely correct. By doing `dateutil.parser.parse(value).date()`, you're truncating the datetime to just the date, dropping the time. According to the spec [1], the cell has value-type=date it can have just a date in yyyy-mm-dd or date+time in yyy-mm-ddThh:mm:ss format. So, you need to return a datetime in that case.
Perhaps...
`if len(value) <11:
  return ret.date()
return ret`
although this would make the API inconsistent, so datetime should perhaps be preferred.

I copy pasted the code locally, and that problem obviously shows up.

Thanks for your time though :)

[1] http://books.evc-cit.info/odbook/ch05.html#table-number-cells-section (I hope this link is good)

**Comment by chfw** [comment]
Feedback accepted. Will act on it when time is available.

**Comment by chfw** [comment]
How about the new fix?

**Comment by chfw** [comment]
released to pypi

**Comment by joaoe** [comment]
Hi again. Sorry, I was away,

Now the code chokes on the following input 
2015-08-17T19:09:59.999999
... :/ still output by libreoffice.

Perhaps adding an extra 3rd iff to that block
```python
    elif len(value) > 19:
        ret = datetime.datetime.strptime(value[0:26], "%Y-%m-%dT%H:%M:%S.%f")
    else:
        raise Exception("Bad date format: " + value)
```

**Comment by chfw** [comment]
hmm... libreoffice violates this spec then:

    > The value is stored in a office:date-value attribute rather than a office:value. 
    > If it contains a simple date, it is stored in the form yyyy-mm-dd; if there is 
    > both a day and a time, it is stored in the form yyyy-mm-ddThh:mm:ss. 

But the practice rules over the theory always. I will amend it when I got a slack time.

**Comment by chfw** [comment]
how about this one?

**Comment by joaoe** [comment]
Those two raises plus the try seem redundant.
Moreover, the code now looks a bit bloated. Up to you if you want to keep it that way, although you could simplify it with the tip I gave in the second comment.

I'm currently using libre office 4.3.7.2. So if you have that one, try to save the date "2015-08-17T19:10:00" in a cell with a custom datetime format and see if it saves the timestamp with decimal places in case you want to see the weirdness happen.

**Comment by chfw** [comment]
pump up to 0.0.11 in pypi.
