### ISSUE TITLE
Symption: Problem opening ODS file - Actual problem: excessive trailing columns with empty values

### ISSUE THREAD

**Issue by psychemedia** [chfw/pyexcel-ods#4]
Seems like there may be ODS files that pyexcel-ods struggles with?

eg [UKgov housing data](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/374580/LiveTable_122.ods) (via [here](https://www.gov.uk/government/statistical-data-sets/live-tables-on-dwelling-stock-including-vacants)).

I can see elements of it in pandas, eg using:

    import pandas as pd
    pd.DataFrame.from_dict(data,orient='index')

or

    pd.DataFrame.from_dict(data)

so it's getting something out...

But if I try to inspect the parsed object or cast it to JSON, it just hangs my python environment (so a deep level of nesting going on in there?).

Also, the data has datetimes in it which causes causes the example `json.loads()` viewer to fail. I found a [simple fix on StackOverflow](http://stackoverflow.com/a/25895504/454773).

**Comment by chfw** [comment]
which file is it? and what kind of problem you are having? I have tried "LiveTable_12x.ods" and all three were opened.

**Comment by psychemedia** [comment]
LiveTable_122.ods - using a relatively recent anaconda ipython 2.7

Okay - just did another test using the git version of `pyexcel-ods` and it seems the problem is with the IPython notebook I'm using to try to look at the data.

The data is a list of lists starting `[[u'Table 122 Net additional dwellingsby local authority district, England 2004-05 to 2013-14', '','',...` but the rows are hugely long and full of empty cols?

Individual rows look like eg:

    ['', u'F0114', u'00HA', u'E06000022', '', u'Bath and North East Somerset UA', '', \
    150.0, 170.0, 260.0, 500.0, 380.0, 350.0, 240.0, 460.0, 550.0, 550.0, '', '',...for a very long time...'']

That is, it's including lots of empty columns on the right hand side?

**Comment by chfw** [comment]
pyexcel flattens the data matrix, for example:

from this source:

   1
    2,3,
    4,5,6

to:
   1,'',''
   2,3,''
   4,5,6

I will look at this extra long empty column problem.

**Comment by chfw** [comment]
released to pypi. please give it a go and let me know if that satisfy your requirement or not.

**Comment by psychemedia** [comment]
Yes - seems to work much better now. Thanks:-)

**Comment by chfw** [comment]
Thanks for letting me know. Nice to hear it works. Any other issues, please log them here or a new one.
